### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lt1089-Coder** [happymimimix/midi2flp-CPP#1]
The software will exit the program when opening a MIDI file with a width of 256.

**Comment by happymimimix** [comment]
You mean 256 keys?

**Comment by happymimimix** [comment]
![image](https://github.com/user-attachments/assets/0006dc56-4d33-4be7-a202-1f67c96c3c4f)
I replicated that successfully with the 256 keys mod of domino. 
This is the problem of the midi parsing library I'm using. 
MIDIfiles.h is not expecting any value to be greater than 0x7F in the midi file. It would throw an error if it detected events with value greater than 0x7F. 
This should be easy to resolve, just remove the if statements that does this detection in the library. 
My code should not have any issue at handling 256k midis in theory.

**Comment by happymimimix** [comment]
Result: 
![image](https://github.com/user-attachments/assets/76a161f3-3d73-45e5-a337-edefa1840152)
![image](https://github.com/user-attachments/assets/141572b1-3028-4b36-b2f4-1a24b15e412b)

**Comment by happymimimix** [comment]
https://github.com/happymimimix/midi2flp-CPP/releases/tag/002
